### ISSUE TITLE
cpu2017 on P8 miscompares with 500.perlbench_r 

### ISSUE THREAD

**Issue by kachini** [open-power/op-benchmark-recipes#7]
I'm running CPU2017 on a P8 machine built with xlC/at11.0 and getting miscompares with 500.perlbench_r: 

Any idea? 

Running Benchmarks
  Running (#1) 500.perlbench_r test base P8_4S (1 copy) [2018-08-10 19:39:24]
Error with '/home/cpu2017/bin/specinvoke -d /home/cpu2017//p8_4S/benchspec/CPU/500.perlbench_r/run/run_base_test_P8_4S.0000 -f compare.cmd -E -e compare.err -o compare.stdout'; no non-empty output files exist
  Command returned exit code 1

***** Miscompare of test.out; for details see**
    /home/cpu2017//p8_4S/benchspec/CPU/500.perlbench_r/run/run_base_test_P8_4S.0000/test.out.mis
Invalid run; unable to continue.
If you wish to ignore errors please use '-I' or ignore_errors

The log for this run is in /home/cpu2017//p8_4S/result/CPU2017.002.log
The debug log for this run is in /home/cpu2017//p8_4S/result/CPU2017.002.log.debug

*
* Temporary files were NOT deleted; keeping temporaries such as
* /home/cpu2017//p8_4S/result/CPU2017.002.log.debug and
* /home/cpu2017//p8_4S/tmp/CPU2017.002
* (These may be large!)
*
runcpu finished at 2018-08-10 19:40:02; 44 total seconds elapsed
[root@localhost cpu2017]# cat /home/cpu2017//p8_4S/benchspec/CPU/500.perlbench_r/run/run_base_test_P8_4S.0000/test.out.mis
0254:  t/run/noswitch .............................. ok
       t/run/noswitch .............................. 
                                                   ^
'test.out' short
[root@localhost cpu2017]#

**Comment by johnjmartinez** [comment]
Hello,
My apologies for the delayed response.
Looking at the error and consulting with others, we think the issue lies on the P9 configuration file, which is not meant for direct use on P8 without tweaking it first.

In the `LE64Test_P9.cfg` config file the line:
`EXTRA_COPTIMIZE = -O5 -qarch=pwr9 -qtune=pwr9`
should be:
`EXTRA_COPTIMIZE = -O5 -qarch=pwr8 -qtune=pwr8`

Also, please ensure that the cpu binding corresponds to the system-under-test's characteristics.
Let me know if this works or not.
-JM

**Comment by johnjmar** [comment]
Hello,
My apologies for the delayed response.
Looking at the error and consulting with others, we think the issue lies on the P9 configuration file, which is not meant for direct use on P8 without tweaking it first.

In the `LE64Test_P9.cfg` config file, the line:
`EXTRA_COPTIMIZE = -O5 -qarch=pwr9 -qtune=pwr9`
should be:
`EXTRA_COPTIMIZE = -O5 -qarch=pwr8 -qtune=pwr8`

Also, please ensure that the cpu binding corresponds to the system-under-test's characteristics.
Let me know if this works or not.
-JM

**Comment by kachini** [comment]
sure, i swapped pwr8 <=> pwr9 at very beginning. Also i adjusted numa settings but it shouldn't make sense because i'm running copies=1 and still see miscompares

**Comment by kachini** [comment]
fixed by re-installing full environment from scratch

**Comment by johnjmar** [comment]
Closing for now.
Please reopen if you see behavior again.
